<template>
  <div class="setting-panel-gui">
    <g-field
      label=""
    >
      <g-input
        v-model="config.title"
      />
    </g-field>
    <g-field-collapse
      label=""
    >
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.textStyle.fontFamily"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input-number
          v-model="config.textStyle.fontSize"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.textStyle.color"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.textStyle.fontWeight"
        />
      </g-field>
    </g-field-collapse>
    <g-field
      label=""
    >
      <g-input
        v-model="config.textAlign"
      />
    </g-field>
    <g-field
      label=""
    >
      <g-input
        v-model="config.writingMode"
      />
    </g-field>
    <g-field
      label=""
    >
      <g-input-number
        v-model="config.letterSpacing"
        :min="0"
        :max="100"
        :step="1"
      />
    </g-field>
    <g-field-collapse
      label=""
    >
      <g-field
        :level="2"
        label=""
      >
        <n-switch
          v-model:value="config.backgroundStyle.show"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.backgroundStyle.bgColor"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input-number
          v-model="config.backgroundStyle.borderRadius"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.backgroundStyle.borderColor"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.backgroundStyle.borderStyle"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input-number
          v-model="config.backgroundStyle.borderWidth"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
    </g-field-collapse>
    <g-field
      label=""
    >
      <n-switch
        v-model:value="config.ellipsis"
      />
    </g-field>
    <g-field-collapse
      label=""
    >
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.urlConfig.url"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <n-switch
          v-model:value="config.urlConfig.isBlank"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      label=""
    >
      <g-field
        :level="2"
        label=""
      >
        <n-switch
          v-model:value="config.animation.enable"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.animation.name"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input-number
          v-model="config.animation.duration"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.animation.timing"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input-number
          v-model="config.animation.delay"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.animation.iteration"
        />
      </g-field>
      <g-field
        :level="2"
        label=""
      >
        <g-input
          v-model="config.animation.direction"
        />
      </g-field>
    </g-field-collapse>
    <g-field
      label=""
    >
      <g-input
        v-model="config.cursor"
      />
    </g-field>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
} from '@/data/select-options'
import { MainTitle2 } from './main-title2'

export default defineComponent({
  name: 'VMainTitle2Prop',
  props: {
    com: {
      type: Object as PropType<MainTitle2>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    return {
      config,

    }
  },
})
</script>
